update build workflow, with test and release of sqlite-sync

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,13 +1,14 @@
-name: build sqlitesync
+name: build, test and release sqlite-sync
 on:
   push:
-    branches:
-      - main
+
+permissions:
+  contents: write
 
 jobs:
   build:
     runs-on: ${{ matrix.os }}
-    name: build for ${{ matrix.name }}-${{ matrix.arch }}
+    name: ${{ matrix.name }}${{ matrix.arch && format('-{0}', matrix.arch) || '' }} build${{ matrix.arch != 'arm64-v8a' && matrix.name != 'isim' && matrix.name != 'ios' && ' + test' || ''}}
     timeout-minutes: 20
     strategy:
       fail-fast: false
@@ -34,7 +35,7 @@ jobs:
             configure: --with-schannel
             name: windows
           - os: ubuntu-latest
-            arch: arm64
+            arch: arm64-v8a
             configure:
               --host aarch64-linux-android26
               --with-openssl=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr
@@ -47,6 +48,9 @@ jobs:
               RANLIB=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib
               STRIP=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip
             name: android
+            make:
+              PLATFORM=android
+              CC=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android26-clang
           - os: ubuntu-latest
             arch: x86_64
             configure:
@@ -61,6 +65,10 @@ jobs:
               RANLIB=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib
               STRIP=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip
             name: android
+            make:
+              PLATFORM=android
+              CC=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android26-clang
+            sqlite-amalgamation-zip: https://sqlite.org/2025/sqlite-amalgamation-3490100.zip
           - os: macos-latest
             arch: arm64
             configure:
@@ -68,6 +76,7 @@ jobs:
               --with-secure-transport
               CFLAGS="-arch arm64 -isysroot $(xcrun --sdk iphoneos --show-sdk-path) -miphoneos-version-min=11.0"
             name: ios
+            make: PLATFORM=ios
           - os: macos-latest
             arch: arm64
             configure:
@@ -75,6 +84,7 @@ jobs:
               --with-secure-transport
               CFLAGS="-arch arm64 -isysroot $(xcrun --sdk iphonesimulator --show-sdk-path) -miphonesimulator-version-min=11.0"
             name: isim
+            make: PLATFORM=isim
           - os: macos-latest
             arch: x86_64
             configure:
@@ -82,6 +92,7 @@ jobs:
               --with-secure-transport
               CFLAGS="-arch x86_64 -isysroot $(xcrun --sdk iphonesimulator --show-sdk-path) -miphonesimulator-version-min=11.0"
             name: isim
+            make: PLATFORM=isim
 
     defaults:
       run:
@@ -208,12 +219,113 @@ jobs:
           mkdir -p network/curl/${{ matrix.name }}
           mv $folder/lib/.libs/libcurl.a network/curl/${{ matrix.name }}/lib${{matrix.arch}}.a
 
+      - name: build sqlite-sync
+        run: make ${{ matrix.make && matrix.make || ''}}
+
+      - name: windows install sqlite3
+        if: matrix.os == 'windows-latest'
+        run: choco install sqlite -y
+
+      - name: macos install sqlite3 without SQLITE_OMIT_LOAD_EXTENSION
+        if: matrix.name == 'macos'
+        run: brew link sqlite --force
+
+      - name: android setup test environment
+        if: matrix.name == 'android' && matrix.arch != 'arm64-v8a'
+        run: |
+
+          echo "::group::enable kvm group perms"
+          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
+          sudo udevadm control --reload-rules
+          sudo udevadm trigger --name-match=kvm
+          echo "::endgroup::"
+
+          echo "::group::download and build sqlite3 without SQLITE_OMIT_LOAD_EXTENSION"
+          curl -O ${{ matrix.sqlite-amalgamation-zip }}
+          unzip sqlite-amalgamation-*.zip
+          export ${{ matrix.make }}
+          $CC sqlite-amalgamation-*/shell.c sqlite-amalgamation-*/sqlite3.c -o sqlite3 -ldl
+          rm -rf sqlite-amalgamation-*.zip sqlite-amalgamation-*
+          echo "::endgroup::"
+
+          echo "::group::prepare the test script"
+          make test CC=$CC PLATFORM=$PLATFORM || echo "It should fail. Running remaining commands in the emulator"
+          cat > commands.sh << EOF
+            mv -f /data/local/tmp/sqlite3 /system/xbin
+            cd /data/local/tmp
+            $(make test CC=$CC PLATFORM=$PLATFORM -n)
+          EOF
+          echo "::endgroup::"
+
+      - name: android test sqlite-sync
+        if: matrix.name == 'android' && matrix.arch != 'arm64-v8a'
+        uses: reactivecircus/android-emulator-runner@v2.34.0
+        with:
+          api-level: 26
+          arch: ${{ matrix.arch }}
+          script: |
+            adb root
+            adb remount
+            adb push ${{ github.workspace }}/. /data/local/tmp/
+            adb shell "sh /data/local/tmp/commands.sh"
+
+      - name: test sqlite-sync
+        if: matrix.name == 'linux' || matrix.name == 'macos' || matrix.name == 'windows'
+        run: make test
+
       - uses: actions/upload-artifact@v4.6.2
         with:
-          name: libcurl-${{ matrix.name }}-${{ matrix.arch }}
-          path: network/curl/${{ matrix.name }}/lib${{matrix.arch}}.a
+          name: cloudsync-${{ matrix.name }}${{ matrix.arch && format('-{0}', matrix.arch) || '' }}
+          path: dist/cloudsync.*
           if-no-files-found: error
 
-      - name: build sqlitesync
+  release:
+    runs-on: ubuntu-latest
+    name: release
+    needs: build
+    if: github.ref == 'refs/heads/main'
+
+    env:
+      GH_TOKEN: ${{ github.token }}
+
+    steps:
+
+      - uses: actions/checkout@v4.2.2
+
+      - uses: actions/download-artifact@v4.2.1
+        with:
+          path: artifacts
+
+      - name: release tag version from cloudsync.h
+        id: tag
         run: |
-          echo "TODO: build sqlitesync"
+          FILE="src/cloudsync.h"
+          VERSION=$(grep -oP '#define CLOUDSYNC_VERSION\s+"\K[^"]+' "$FILE")
+          if [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "version=$VERSION" >> $GITHUB_OUTPUT
+            exit 0
+          fi
+          echo "❌ CLOUDSYNC_VERSION not found in cloudsync.h"
+          exit 1
+          
+      - name: zip artifacts
+        run: |
+          for folder in "artifacts"/*; do
+            if [ -d "$folder" ]; then
+              name=$(basename "$folder")
+              zip -jq "${name}-${{ steps.tag.outputs.version }}.zip" "$folder"/*
+              tar -cJf "${name}-${{ steps.tag.outputs.version }}.tar.xz" -C "$folder" .
+              tar -czf "${name}-${{ steps.tag.outputs.version }}.tar.gz" -C "$folder" .
+            fi
+          done
+
+      - uses: softprops/action-gh-release@v2.2.1
+        with:
+          generate_release_notes: true
+          tag_name: ${{ steps.tag.outputs.version }}
+          files: |
+            cloudsync-*-${{ steps.tag.outputs.version }}.zip
+            cloudsync-*-${{ steps.tag.outputs.version }}.tar.xz
+            cloudsync-*-${{ steps.tag.outputs.version }}.tar.gz
+          make_latest: true
+
