build dependencies in the makefile to allow full local builds (#2)
* curl build in the makefile

* android fix new line and arch in tests

* android define curl config inline

* android fix lowercase uname -s

* fix windows

* android typos

* android arch override

* android dynamic curl config

* android set cc in the makefile

* makefile set android ndk path

* win build with msys test

* remove msys from makefile

* windows use msys bash

* makefile windows use msys make

* fix: quote msys make command for Windows compatibility

* android build openssl in the makefile

* fix android openssl prefix

* makefile android fix curl dependencies

* android fix makefile run recipe only one time

* fix android makefile only openssl dependency

* makefile fix windows make path

* fix makefile to use msys bash for curl build on Windows

* fix makefile spacing

* fix makefile tab

* fix makefile to use mingw64 make for Windows build

* fix: update Windows build process for curl

* fix: set default shell to bash in GitHub Actions workflow

* fix: optimize make commands for parallel execution in GitHub Actions and Makefile

* fix: replace make command with $(MAKE) for consistency and speed up in build openssl

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,78 +18,34 @@ jobs:
         include:
           - os: ubuntu-latest
             arch: x86_64
-            configure: --with-openssl
             name: linux
           - os: LinuxARM64
             arch: arm64
-            configure: --with-openssl
             name: linux
           - os: macos-latest
-            configure:
-              --with-secure-transport
-              CFLAGS="-arch x86_64 -arch arm64"
             name: macos
           - os: windows-latest
             arch: x86_64
-            configure:
-              --with-schannel
-              CFLAGS="-DCURL_STATICLIB"
             name: windows
           - os: ubuntu-latest
             arch: arm64-v8a
-            configure:
-              --host aarch64-linux-android26
-              --with-openssl=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr
-              LIBS="-lssl -lcrypto"
-              AR=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar
-              AS=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-as
-              CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android26-clang
-              CXX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android26-clang++
-              LD=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/ld
-              RANLIB=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib
-              STRIP=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip
             name: android
-            make:
-              PLATFORM=android
-              CC=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android26-clang
+            make: PLATFORM=android ARCH=arm64-v8a
           - os: ubuntu-latest
             arch: x86_64
-            configure:
-              --host x86_64-linux-android26
-              --with-openssl=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr
-              LIBS="-lssl -lcrypto"
-              AR=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar
-              AS=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-as
-              CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android26-clang
-              CXX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android26-clang++
-              LD=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/ld
-              RANLIB=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib
-              STRIP=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip
             name: android
-            make:
-              PLATFORM=android
-              CC=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android26-clang
+            make: PLATFORM=android ARCH=x86_64
             sqlite-amalgamation-zip: https://sqlite.org/2025/sqlite-amalgamation-3490100.zip
           - os: macos-latest
-            configure:
-              --host=arm64-apple-darwin
-              --with-secure-transport
-              CFLAGS="-arch arm64 -isysroot $(xcrun --sdk iphoneos --show-sdk-path) -miphoneos-version-min=11.0"
             name: ios
             make: PLATFORM=ios
           - os: macos-latest
-            configure:
-              --host=arm64-apple-darwin
-              --with-secure-transport
-              CFLAGS="-arch x86_64 -arch arm64 -isysroot $(xcrun --sdk iphonesimulator --show-sdk-path) -miphonesimulator-version-min=11.0"
             name: isim
             make: PLATFORM=isim
 
     defaults:
       run:
-        shell: ${{ matrix.os == 'windows-latest' && 'msys2 {0}' || 'bash' }}
-    env:
-      MAKEFLAGS: -j 8
+        shell: bash
 
     steps:
 
@@ -101,123 +57,19 @@ jobs:
           msystem: mingw64
           install: >-
             mingw-w64-x86_64-cc
-            mingw-w64-x86_64-autotools make
+            make
 
-      - uses: robinraju/release-downloader@v1.12
-        with:
-          repository: curl/curl
-          tag: 'curl-8_12_1'
-          extract: true
-          fileName: curl-*.tar.gz
-
-      - name: build openssl
-        if: matrix.name == 'android'
-        run: |
-          git clone https://github.com/openssl/openssl.git
-          cd openssl
-          export TOOLCHAIN=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64
-          export ARCH=${{ matrix.arch }}
-          export PATH=$TOOLCHAIN/bin:$PATH
-
-          ./Configure android-${{ matrix.arch == 'arm64-v8a' && 'arm64' || matrix.arch }} \
-            --prefix=$PWD/build \
-            --openssldir=$PWD/build/ssl \
-            no-shared \
-            no-unit-test \
-            -D__ANDROID_API__=26
-          make
-          make install_sw
-
-          cp build/lib/libssl.a $TOOLCHAIN/sysroot/usr/lib/
-          cp build/lib/libcrypto.a $TOOLCHAIN/sysroot/usr/lib/
-          cp -r build/include/openssl $TOOLCHAIN/sysroot/usr/include/
-          
-      - name: build curl
-        run: |
-        
-          folder=$(ls -d curl-*/ 2>/dev/null | head -n 1)
-          cd $folder
-
-          ./configure \
-            --without-libpsl \
-            --disable-alt-svc \
-            --disable-ares \
-            --disable-cookies \
-            --disable-basic-auth \
-            --disable-digest-auth \
-            --disable-kerberos-auth \
-            --disable-negotiate-auth \
-            --disable-aws \
-            --disable-dateparse \
-            --disable-dnsshuffle \
-            --disable-doh \
-            --disable-form-api \
-            --disable-hsts \
-            --disable-ipv6 \
-            --disable-libcurl-option \
-            --disable-manual \
-            --disable-mime \
-            --disable-netrc \
-            --disable-ntlm \
-            --disable-ntlm-wb \
-            --disable-progress-meter \
-            --disable-proxy \
-            --disable-pthreads \
-            --disable-socketpair \
-            --disable-threaded-resolver \
-            --disable-tls-srp \
-            --disable-verbose \
-            --disable-versioned-symbols \
-            --enable-symbol-hiding \
-            --without-brotli \
-            --without-zstd \
-            --without-libidn2 \
-            --without-librtmp \
-            --without-zlib \
-            --without-nghttp2 \
-            --without-ngtcp2 \
-            --disable-shared \
-            --disable-ftp \
-            --disable-file \
-            --disable-ipfs \
-            --disable-ldap \
-            --disable-ldaps \
-            --disable-rtsp \
-            --disable-dict \
-            --disable-telnet \
-            --disable-tftp \
-            --disable-pop3 \
-            --disable-imap \
-            --disable-smb \
-            --disable-smtp \
-            --disable-gopher \
-            --disable-mqtt \
-            --disable-docs \
-            --enable-static \
-            ${{matrix.configure}}
-          make
-            
-            # save avg 1kb more with these options
-            # --disable-debug \
-            # --enable-optimize \
-            # --disable-curldebug \
-            # --disable-get-easy-options \
-            # --without-fish-functions-dir \
-            # --without-zsh-functions-dir \
-            # --without-libgsasl \
-
-          cd ..
-          mkdir -p curl/${{ matrix.name }}
-          mv $folder/lib/.libs/libcurl.a curl/${{ matrix.name }}
+      - name: windows build curl
+        if: matrix.os == 'windows-latest'
+        run: make curl/windows/libcurl.a -j4
+        shell: msys2 {0}
 
       - name: build sqlite-sync
-        run: make ${{ matrix.make && matrix.make || ''}}
-        shell: bash
+        run: make extension ${{ matrix.make && matrix.make || ''}} -j4
 
       - name: windows install sqlite3
         if: matrix.os == 'windows-latest'
         run: choco install sqlite -y
-        shell: bash
 
       - name: macos install sqlite3 without SQLITE_OMIT_LOAD_EXTENSION
         if: matrix.name == 'macos'
@@ -237,17 +89,17 @@ jobs:
           curl -O ${{ matrix.sqlite-amalgamation-zip }}
           unzip sqlite-amalgamation-*.zip
           export ${{ matrix.make }}
-          $CC sqlite-amalgamation-*/shell.c sqlite-amalgamation-*/sqlite3.c -o sqlite3 -ldl
+          $ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/${{ matrix.arch }}-linux-android26-clang sqlite-amalgamation-*/shell.c sqlite-amalgamation-*/sqlite3.c -o sqlite3 -ldl
           # remove unused folders to save up space
-          rm -rf sqlite-amalgamation-*.zip sqlite-amalgamation-* curl-* openssl
+          rm -rf sqlite-amalgamation-*.zip sqlite-amalgamation-* openssl
           echo "::endgroup::"
 
           echo "::group::prepare the test script"
-          make test CC=$CC PLATFORM=$PLATFORM || echo "It should fail. Running remaining commands in the emulator"
+          make test PLATFORM=$PLATFORM ARCH=$ARCH -j4 || echo "It should fail. Running remaining commands in the emulator"
           cat > commands.sh << EOF
             mv -f /data/local/tmp/sqlite3 /system/xbin
             cd /data/local/tmp
-            $(make test CC=$CC PLATFORM=$PLATFORM -n)
+            $(make test PLATFORM=$PLATFORM ARCH=$ARCH -n)
           EOF
           echo "::endgroup::"
 
@@ -265,8 +117,7 @@ jobs:
 
       - name: test sqlite-sync
         if: matrix.name == 'linux' || matrix.name == 'windows'
-        run: make test
-        shell: bash
+        run: make test -j4
 
       - name: test sqlite-sync + coverage
         if: matrix.name == 'macos'
