new integration test (#4)
* feat: init integration tests

* fix: optimize build commands and improve CPU utilization in Makefile

* New Android PEM specific code

* fix android cert: add new line

* refactor: remove health-track schema and update db_init function for improved initialization

* refactor: improve error handling and add in memory peers test

* refactor: multi-threaded sync testing with random text insert

* expect sync to be gt0 only when not initializing the db

* to fix test

* test only 5 peers

* test 2 peers

* test: expect changes gt0 only when not initializing the db

* test: low peers count

* fix integration test: add windows thread handling

* fix: rename INT to INTGR in expected_type enum to avoid redeclaration issues

* test 1 peer

* add max retry and wait time

* increase wait time and retries

* Resolve cacert.h merge conflicts

* test print network sync results

* sync test skip insert

* test print network init string

* test: remove debug prints

* test: update PEERS count and modify cloudsync_network_sync parameters

* test: lower peers count

* test: missing close database connection after initialization

* linux error test

* revert last test commit

* test debug functions and settings

* test 1 peer

* test 2 peer

* print cloudsync_network_sync

* test: disable debug flags

* test more peers

* final test 50 peers

* remove debug network sync print

* test 10 peers

* expect network sync to be gt0

* hardcode test executables

* fix makefile link pthread

* revert last commits

* lower peers count

---------

Co-authored-by: Marco Bambini <marco@creolabs.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -48,6 +48,11 @@ jobs:
       run:
         shell: bash
 
+    env:
+      CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
+      APIKEY: ${{ secrets.APIKEY }}
+      WEBLITE: ${{ secrets.WEBLITE }}
+
     steps:
 
       - uses: actions/checkout@v4.2.2
@@ -62,11 +67,11 @@ jobs:
 
       - name: windows build curl
         if: matrix.os == 'windows-latest'
-        run: make curl/windows/libcurl.a -j4
+        run: make curl/windows/libcurl.a
         shell: msys2 {0}
 
       - name: build sqlite-sync
-        run: make extension ${{ matrix.make && matrix.make || ''}} -j4
+        run: make extension ${{ matrix.make && matrix.make || ''}}
 
       - name: windows install sqlite3
         if: matrix.os == 'windows-latest'
@@ -96,10 +101,13 @@ jobs:
           echo "::endgroup::"
 
           echo "::group::prepare the test script"
-          make test PLATFORM=$PLATFORM ARCH=$ARCH -j4 || echo "It should fail. Running remaining commands in the emulator"
+          make test PLATFORM=$PLATFORM ARCH=$ARCH || echo "It should fail. Running remaining commands in the emulator"
           cat > commands.sh << EOF
             mv -f /data/local/tmp/sqlite3 /system/xbin
             cd /data/local/tmp
+            export CONNECTION_STRING="$CONNECTION_STRING"
+            export APIKEY="$APIKEY"
+            export WEBLITE="$WEBLITE"
             $(make test PLATFORM=$PLATFORM ARCH=$ARCH -n)
           EOF
           echo "::endgroup::"
@@ -118,7 +126,7 @@ jobs:
 
       - name: test sqlite-sync
         if: matrix.name == 'linux' || matrix.name == 'windows'
-        run: make test -j4
+        run: make test
 
       - name: test sqlite-sync + coverage
         if: matrix.name == 'macos'
