fix: optimize build commands and improve CPU utilization in Makefile

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -66,11 +66,11 @@ jobs:
 
       - name: windows build curl
         if: matrix.os == 'windows-latest'
-        run: make curl/windows/libcurl.a -j4
+        run: make curl/windows/libcurl.a
         shell: msys2 {0}
 
       - name: build sqlite-sync
-        run: make extension ${{ matrix.make && matrix.make || ''}} -j4
+        run: make extension ${{ matrix.make && matrix.make || ''}}
 
       - name: windows install sqlite3
         if: matrix.os == 'windows-latest'
@@ -100,7 +100,7 @@ jobs:
           echo "::endgroup::"
 
           echo "::group::prepare the test script"
-          make test PLATFORM=$PLATFORM ARCH=$ARCH -j4 || echo "It should fail. Running remaining commands in the emulator"
+          make test PLATFORM=$PLATFORM ARCH=$ARCH || echo "It should fail. Running remaining commands in the emulator"
           cat > commands.sh << EOF
             mv -f /data/local/tmp/sqlite3 /system/xbin
             cd /data/local/tmp
@@ -125,7 +125,7 @@ jobs:
 
       - name: test sqlite-sync
         if: matrix.name == 'linux' || matrix.name == 'windows'
-        run: make test -j4
+        run: make test
 
       - name: test sqlite-sync + coverage
         if: matrix.name == 'macos'
